# Generated by Django 3.2.4 on 2021-06-23 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='tittle',
            new_name='title',
        ),
    ]
